@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 28 15:49:14 +0800 2025
REM SW Build 6233196 on Thu Sep 11 21:27:30 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_keypad_scanner_behav -key {Behavioral:sim_1:Functional:tb_keypad_scanner} -tclbatch tb_keypad_scanner.tcl -view C:/Users/ryanh/fpga/digital-system-design/keypad_scanner/tb_keypad_scanner_behav.wcfg -log simulate.log"
call xsim  tb_keypad_scanner_behav -key {Behavioral:sim_1:Functional:tb_keypad_scanner} -tclbatch tb_keypad_scanner.tcl -view C:/Users/ryanh/fpga/digital-system-design/keypad_scanner/tb_keypad_scanner_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
